<a href="https://colab.research.google.com/github/kartikgugadaddi771-collab/KARTIK-GUGADADDI/blob/main/NumPy_Assignment_ipynb_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [ ]:
#1)The finance manager wants to confirm how many stores and product categories are present in the data.

#Write NumPy code to display:

#Number of dimensions in sales_data
#Shape of sales_data
#Total number of values
#Data type of the array
#Memory occupied by the arra
(sales_data.ndim,
sales_data.shape,
type(sales_data),
sales_data.size,
sales_data.nbytes
)


(2, (5, 6), numpy.ndarray, 30, 240)

In [ ]:
#2)Calculate the following:

#Total number of stores
#Total number of product categories
#Total number of store-category combinations
(
stores.shape[0],
categories.shape[0],
stores.shape[0]*categories.shape[0]
)




(5, 6, 30)

In [ ]:
#3)The reporting application requires sales values in floating-point format.

#Convert sales_data into:

#float32
#float64
#Compare the memory used by both arrays.
import numpy as np
sales_data_32=sales_data.astype(np.float32,)
sales_data_64=sales_data.astype(np.float64)
print(f"memory occupied by sales_data(float 32): {sales_data_32.nbytes} bytes")
print(f"memory occupied by sales_data(float 64): {sales_data_64.nbytes} bytes")


memory occupied by sales_data(float 32): 120 bytes
memory occupied by sales_data(float 64): 240 bytes


In [ ]:
#Question 4: Bengaluru Store Analysis
#The Bengaluru regional manager wants to review sales for all product categories.
#Extract and display the complete sales row for Bengaluru.
import numpy as np
bengaluru_index=np.where(stores == "Bengaluru")[0][0]
bengaluru_sales=sales_data[bengaluru_index]
print(f"sales data for bengaluru :{bengaluru_sales}")


sales data for bengaluru :[850000. 420000. 310000. 275000. 190000. 225000.]


In [ ]:
#Question 5: Mumbai Cost Analysis
#Extract the total cost incurred by the Mumbai store for all product categories.
import numpy as np
mumbai_index=np.where(stores=="Mumbai")[0][0]
mumbai_cost_data=cost_data[mumbai_index]
total_cost=np.sum(mumbai_cost_data)
print(f' mumbai total cost for all product : {total_cost}')



 mumbai total cost for all product : 2065000


In [ ]:
#Question 6: Electronics Sales Across Stores
#The electronics department wants to compare its sales performance across all five stores.
#Extract the Electronics sales column from sales_data.
electonics_index=np.where(categories=="Electronics")[0][0]
electonics_sales=sales_data[electonics_index]
print(f'electronics sales across all stores:{electonics_sales}')



electronics sales across all stores:[850000. 420000. 310000. 275000. 190000. 225000.]


In [ ]:
#Question 7: Clothing Cost Across Stores
#Extract the Clothing cost for every store from cost_data.
clothing_index=np.where(categories=="Clothing")[0][0]
clothing_cost=cost_data[clothing_index]
print(f"clothing cost for every store: {clothing_cost}")

clothing cost for every store: [700000 295000 245000 195000 120000 155000]


In [ ]:
#Question 8: Hyderabad Furniture Performance
#Find the following for Hyderabad:
#Furniture sales
#Furniture cost
#Furniture profit
stores_hyderabad_index=np.where(stores=="Hyderabad")[0][0]
furniture_index=np.where(categories=="Furniture")[0][0]
furniture_sales_data=sales_data[stores_hyderabad_index,furniture_index]
furniture_cost_data=cost_data[stores_hyderabad_index,furniture_index]
profit_furniture=furniture_sales_data - furniture_cost_data
print(f" sales of hyderbad furniture :{furniture_sales_data}")
print(f" cost of hyderabad furniture :{furniture_cost_data}")
print(f" furniture profit of hyderabad : {profit_furniture}")


 sales of hyderbad furniture :310000.0
 cost of hyderabad furniture :225000
 furniture profit of hyderabad : 85000.0


In [ ]:
#Question 9: Chennai Category Range
#Extract Chennai’s sales for the following categories:
#Groceries
#Clothing
#Furniture
#Use array slicing.
chennai_index=np.where(stores=="Chennai")[0][0]
clothing_index=np.where(categories=="Clothing")[0][0]
Groceries_index=np.where(categories=="Groceries")[0][0]
Furniture_index=np.where(categories=="Furniture")[0][0]
categories_index=[clothing_index,Groceries_index,Furniture_index]
chennai_sales=sales_data[chennai_index,categories_index]
print(f"chennai selected categories sales:{chennai_sales}")


chennai selected categories sales:[340000. 390000. 260000.]


In [ ]:
#Question 10: Selected Store Analysis
#Extract sales data for:
#Bengaluru
#Chennai
#Pune
#Include only:

#Electronics
#Clothing
#Beauty
#Use advanced indexing.
import numpy as np


selected_stores = ["Bengaluru", "Chennai", "Pune"]
stores_indices = np.array([np.where(stores == store_name)[0][0] for store_name in selected_stores])

selected_categories = ["Electronics", "Clothing", "Beauty"]
categories_indices = np.array([np.where(categories == category_name)[0][0] for category_name in selected_categories])
sales_data_stores = sales_data[stores_indices[:, np.newaxis], categories_indices]

print(f"Sales data for selected stores and categories:\n{sales_data_stores}")

Sales data for selected stores and categories:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [ ]:
#Question 11: Company-Wide Sales
#Calculate the total sales revenue generated by all stores and all categories.
import numpy as np
total_sales=np.sum(sales_data)
print(f"total sales generated by all stores and categories : {total_sales}")

total sales generated by all stores and categories : 11675000


In [ ]:
#Question 12: Store-Wise Sales
#Calculate total sales revenue for each store.
#Display the result together with the store names.
import numpy as np
stores=np.array(stores)
sales_data=np.array(sales_data)
store_wise_sales_data=sales_data.sum(axis=1)
for store , total in zip(stores,store_wise_sales_data):
  print(f"{store}:{total}")



Bengaluru:2270000
Hyderabad:2295000
Chennai:2310000
Mumbai:2820000
Pune:1980000


In [ ]:
#Question 13: Category-Wise Sales
#Calculate total sales for each product category across all stores.
#Display each category name with its total sales.
import numpy as np
categories=np.array(categories)
sales_data=np.array(sales_data)
product_wise_sales=sales_data.sum(axis=0)
for product,total in zip(categories,product_wise_sales):
  print(f"{product}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


In [ ]:
#Question 14: Average Sales Per Store
#Calculate the average sales generated by each store across all six product categories.
import numpy as np
stores_name=np.array(stores)
avg_sales_each_store=sales_data.mean(axis=1)
for store,avg in zip(stores_name,avg_sales_each_store):
  print(f"{store} : {avg}")




Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


In [ ]:
#Question 15: Average Sales Per Category
#Calculate the average sales of each product category across the five stores.
categories=np.array(categories)
avg_sales_each_product=sales_data.mean(axis=0)
for category,avg in zip(categories,avg_sales_each_product):
  print(f"{category}:{avg}")


Electronics:858000.0
Groceries:437000.0
Clothing:320000.0
Furniture:283000.0
Beauty:202000.0
Sports:235000.0


In [ ]:
#Question 16: Highest-Selling Store
#Identify:
#Index of the store with the highest total sales
#Name of the store
#otal sales generated by that store
store_highest_sales=sales_data.sum(axis=1)
max_index=np.argmax(store_highest_sales)
store_name=stores[max_index]
total_sales_store=store_highest_sales[max_index]
print(f'index of store :{max_index}')
print(f"Name of the store : {store_name}")
print(f"Total sales by that store :{total_sales_store}")



index of store :3
Name of the store : Mumbai
Total sales by that store :2820000


In [ ]:
#Question 17: Lowest-Selling Store
#Identify the store with the lowest overall sales.

lowest_selling_store=sales_data.sum(axis=1)
min_index=np.argmin(lowest_selling_store)
store_name=stores[min_index]
total_sales_store=lowest_selling_store[min_index]
print(f"index of store :{min_index}")
print(f"{store_name} is lowest selling store and its total is:{total_sales_store}")

index of store :4
Pune is lowest selling store and its total is:1980000


In [ ]:
#Question 18: Highest-Selling Category
#Find the product category that generated the highest total sales across the company.
highest_selling_category=sales_data.sum(axis=0)
max_index=np.argmax(highest_selling_category)
product_name=categories[max_index]
total_sales_product=highest_selling_category[max_index]
print(f"Index of product is :{max_index}")
print(f"{product_name} has highest sales and its total is :{total_sales_product}")

Index of product is :0
Electronics has highest sales and its total is :4290000


In [ ]:
#Question 19: Lowest-Selling Category
#Find the product category with the lowest total sales across all stores.
lowest_sales_product=sales_data.sum(axis=0)
min_index=np.argmin(lowest_sales_product)
name_product=categories[min_index]
total_sales_product=lowest_sales_product[min_index]
print(f"Index of product:{min_index}")
print(f"{name_product} is lowest selling product and sales is: {total_sales_product}")

Index of product:4
Beauty is lowest selling product and sales is: 1010000


In [ ]:
#Part 5: Cost Analysis
#Question 20: Total Company Cost
#Calculate the total cost incurred by SmartMart across all stores and product categories.
total=cost_data.sum()
print(f"Total cost of company is:{total}")

Total cost of company is 8600000


In [ ]:
#Question 21: Store-Wise Cost
#Calculate the total cost incurred by each store.
import numpy as np
stores=np.array(stores)
np.array(cost_data)
store_wise_cost=cost_data.sum(axis=1)
for store,total in zip(stores,store_wise_cost):
  print(f"{store}:{total}")




Bengaluru:1665000
Hyderabad:1685000
Chennai:1710000
Mumbai:2065000
Pune:1475000


In [ ]:
#Question 22: Category-Wise Cost
#Calculate the total cost incurred for each product category across all stores.
categories=np.array(categories)
cost_data=np.array(cost_data)
categories_wise_cost=cost_data.sum(axis=0)
for product,total in zip(categories,categories_wise_cost):
  print(f"{product}:{total}")


Electronics:3250000
Groceries:1660000
Clothing:1145000
Furniture:1045000
Beauty:665000
Sports:835000


In [ ]:
#Question 23: Most Expensive Store
#Identify the store with the highest total operating cost.
import numpy as np
store_cost_data=cost_data.sum(axis=1)
max_index=np.argmax(store_cost_data)
store_name=stores[max_index]
highest_cost_store=store_cost_data[max_index]
print(f"{store_name} is highest cost store and has:{highest_cost_store}")


Mumbai is highest cost store and has:2065000


In [ ]:
#Question 24: Lowest-Cost Store
#Identify the store with the lowest total cost.
store_cost_data=cost_data.sum(axis=1)
min_index=np.argmin(store_cost_data)
store_name=stores[min_index]
lowest_store_cost=store_cost_data[min_index]
print(f"{store_name} has lowest cost store and total is {lowest_store_cost}")

Pune has lowest cost store and total is 1475000


In [ ]:
#Question 25: Most Expensive Product Category
#Determine which product category has the highest total cost across all stores.
category_cost=cost_data.sum(axis=0)
max_index=np.argmax(category_cost)
product_name=categories[max_index]
highest_cost_product=category_cost[max_index]
print(f"{product_name} has highest product cost: {highest_cost_product}")

Electronics has highest product cost: 3250000


In [ ]:
#Question 26: Profit Matrix
#Calculate the profit generated for every store and product category.
store_city=stores
category=categories
profit_data=sales_data-cost_data
store_profit=profit_data.sum(axis=1)
product_profit=profit_data.sum(axis=0)
for store,profit in zip(store_city,store_profit):
  print(f"{store}:{profit}")
  print("============================")
for product,product_income in zip(category,product_profit):
  print(f"{product}:{product_income}")
  print(f"===========================")




Bengaluru:605000
Hyderabad:610000
Chennai:600000
Mumbai:755000
Pune:505000
Electronics:1040000
Groceries:525000
Clothing:455000
Furniture:370000
Beauty:345000
Sports:340000


In [ ]:
#Question 27: Store-Wise Profit
#Calculate the total profit generated by each store.
stores_city=stores
total_profit=sales_data-cost_data
income=total_profit.sum(axis=1)
for store,profit in zip(stores_city,income):
  print(f"{store} Total profit is :{profit}")


Bengaluru Total profit is :605000
Hyderabad Total profit is :610000
Chennai Total profit is :600000
Mumbai Total profit is :755000
Pune Total profit is :505000


In [ ]:
#Question 28: Category-Wise Profit
#Calculate the total profit generated by each product category.
product_category=categories
total_profit=sales_data-cost_data
income=total_profit.sum(axis=0)
for product,profit in zip(product_category,income):
  print(f"{product} total profit is :{profit}")

Electronics total profit is :1040000
Groceries total profit is :525000
Clothing total profit is :455000
Furniture total profit is :370000
Beauty total profit is :345000
Sports total profit is :340000


In [ ]:
#Question 29: Most Profitable Store
#Identify the store that generated the highest total profit.
#Display:
#Store name
#Total sales
#Total cost
#Total profit
highest_profit_store=sales_data-cost_data
profit_per_store=highest_profit_store.sum(axis=1)
max_index=np.argmax(profit_per_store)
store_name=stores[max_index]
total_sales=sales_data[max_index].sum()
total_cost=cost_data[max_index].sum()
total_profit=profit_per_store[max_index]
print(f"profitable store :{store_name}")
print(f"total cost of store :{total_cost}")
print(f"total sales of store :{total_sales}")
print(f"total profit of store :{total_profit}")

profitable store :Mumbai
total cost of store :2065000
total sales of store :2820000
total profit of store :755000


In [ ]:
#Question 30: Least Profitable Store
#Identify the store that generated the lowest total profit.
lowest_profit_store=sales_data-cost_data
profit_per_stores=lowest_profit_store.sum(axis=1)
min_index=np.argmin(profit_per_store)
store_name=stores[min_index]
store_sales=sales_data[min_index].sum()
store_cost=cost_data[min_index].sum()
total_profit=profit_per_store[min_index]
print(f"less profitable store : {store_name}")
print(f"less sales store: {store_sales}")
print(f"less cost of store : {store_cost}")
print(f"total profit of store :{total_profit}")


less profitable store : Pune
less sales store: 1980000
less cost of store : 1475000
total profit of store :505000


In [ ]:
#Question 31: Most Profitable Category
#Find the category with the highest total profit across all stores.
highest_profit_product=sales_data-cost_data
profit_per_product=highest_profit_product.sum(axis=0)
max_index=np.argmax(profit_per_product)
product_name=categories[max_index]
total_profit=profit_per_product[max_index]
print(f"{product_name} is a highest selling product and profit is {total_profit}")

Electronics is a highest selling product and profit is 1040000


In [ ]:
#Question 32: Least Profitable Category
#Find the category with the lowest total profit.
lowest_profit_product=sales_data-cost_data
profit_per_product=lowest_profit_product.sum(axis=0)
min_index=np.argmin(profit_per_product)
product_name=categories[min_index]
total_profit=profit_per_product[min_index]
print(f"{product_name} is lowest selling product and profit is {total_profit}")


Sports is lowest selling product and profit is 340000


In [ ]:
#Question 33: Maximum Individual Profit
#Find the highest profit generated by any single store-category combination.
#Display:
#Profit amount
#Store name
#Product category
profit=sales_data-cost_data
max_profit=np.argmax(profit)
store_index,categories_index=np.unravel_index(max_profit,profit.shape)
profit_amount=profit[store_index,categories_index]
profit_store_name=stores[store_index]
profit_category_name=categories[categories_index]
print(f"{profit_store_name} {profit_category_name} has highest profit amount :{profit_amount}")





Mumbai Electronics has highest profit amount :260000


In [ ]:
#Question 34: Minimum Individual Profit
#Find the smallest profit generated by a store-category combination.

#Display the corresponding store and category.
profit=sales_data-cost_data
min_profit=np.argmin(profit)
store_index,categories_index=np.unravel_index(min_profit,profit.shape)
profit_amount=profit[store_index,categories_index]
store_name=stores[store_index]
categories_name=categories[categories_index]
print(f"{store_name} {categories_name} has less profit amount:{profit_amount}")


Pune Furniture has less profit amount:55000


In [ ]:
#Question 35: Profit Margin Matrix
#Calculate the profit margin percentage for every store-category combination.
profit_margin=sales_data-cost_data
profit_margin_percentage=(profit_margin/sales_data)*100

print(f"Profit Margin Percentage Matrix:\n{np.round(profit_margin_percentage,2)}")

Profit Margin Percentage Matrix:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [ ]:
#Question 36: Store-Wise Profit Margin
#Calculate the overall profit margin percentage for each store using:
store_name=stores
store_profit_margin=sales_data-cost_data
total_store_profit=store_profit_margin.sum(axis=1)
total_sales_profit=sales_data.sum(axis=1)
overall_profit_percentage=(total_store_profit/total_sales_profit)*100
for store,percent in zip(store_name,overall_profit_percentage):
  print(f"{store}:{round(percent,2)}")


Bengaluru:26.65
Hyderabad:26.58
Chennai:25.97
Mumbai:26.77
Pune:25.51


In [ ]:
#Question 37: Category-Wise Profit Margin
#Calculate the overall profit margin percentage for each product category.
category_name=categories
profit_margin=sales_data-cost_data
total_profit_category=profit_margin.sum(axis=0)
total_sales_profit=sales_data.sum(axis=0)
overall_percentage= (total_profit_category/total_sales_profit)*100
for category,percent in zip(category_name,overall_percentage):
  print(f"{category} {round(percent,2)}")

Electronics 24.24
Groceries 24.03
Clothing 28.44
Furniture 26.15
Beauty 34.16
Sports 28.94


In [ ]:
#Question 38: Best Store by Profit Margin
#Identify the store with the highest overall profit margin.
store_profit=sales_data-cost_data
total_profit_store=store_profit.sum(axis=1)
total_sales_store=sales_data.sum(axis=1)
total_profit_margin= (total_profit_store/total_sales_store)*100
store_index=np.argmax(total_profit_margin)
store_name=stores[store_index]
print(f"{store_name} highest profit margin {total_profit_margin [store_index]:.2f}%")


Mumbai highest profit margin 26.77%


In [ ]:
#Question 39: Best Category by Profit Margin
#Identify the product category with the highest profit margin.
category_profit=sales_data-cost_data
total_profit_category=category_profit.sum(axis=0)
total_sales_category=sales_data.sum(axis=0)
overall_profit_margin=(total_profit_category/total_sales_category)*100
category_index=np.argmax(overall_profit_margin)
category_name=categories[category_index]
print(f"{category_name} has highest profit margin {overall_profit_margin[category_index]:.2f}%")



Beauty has highest profit margin 34.16%


In [ ]:
#Question 40: Low-Margin Transactions
#Management considers a profit margin below 22% to be weak.

#Find all store-category combinations where the profit margin is below 22%.

#Display:
#Store
#Category
#Sales
#Cost
#profit
#Profit margin
profit_matrix=sales_data-cost_data
margin_matrix=(profit_matrix/sales_data)*100
low_margin_22 = margin_matrix<22
store_index,category_index=np.where(low_margin_22)
if len(store_index)==0:
  print(f"no store has margin below 22%")
else:
  for i,j in zip(store_index,category_index):
    print(f"store:{stores[i]}")
    print(f"category:{categories[j]}")
    print(f"sales:{sales_data[i,j]}")
    print(f"cost:{cost_data[i,j]}")
    print(f"profit:{profit_matrix[i,j]}")
    print(f"profit margin :{margin_matrix[i,j]:.2f}%")
    print("-" * 30)


no store has margin below 22%


In [ ]:
#Question 41: High Sales Values
#Find all sales values greater than ₹5,00,000.
high_sales=sales_data > 500000
store_index,category_index=np.where(high_sales)
for i,j in zip(store_index,category_index):
 print(f"store:{stores[i]}")
 print(f"category:{categories[j]}")
 print(f"sales:{sales_data[i,j]}")
 print("-"*10)


store:Bengaluru
category:Electronics
sales:850000
----------
store:Hyderabad
category:Electronics
sales:780000
----------
store:Chennai
category:Electronics
sales:920000
----------
store:Mumbai
category:Electronics
sales:1050000
----------
store:Mumbai
category:Groceries
sales:510000
----------
store:Pune
category:Electronics
sales:690000
----------


In [ ]:
#Question 42: Low Sales Values
#Find all sales values below ₹2,00,000.
low_sales=sales_data<200000
store_index,category_index=np.where(low_sales)
for i,j in zip(store_index,category_index):
 print(f"store:{stores[i]}")
 print(f"category:{categories[j]}")
 print(f"sales:{sales_data[i,j]}")
 print("-"*12)

store:Bengaluru
category:Beauty
sales:190000
------------
store:Chennai
category:Beauty
sales:185000
------------
store:Pune
category:Beauty
sales:175000
------------


In [ ]:
#Question 43: High Profit Values
#Find all store-category combinations where profit is greater than ₹1,50,000.
profit=sales_data-cost_data
high_profit=profit > 150000
store_index,category_index=np.where(high_profit)
for i,j in zip(store_index,category_index):
 print(f"store:{stores[i]}")
 print(f"category:{categories[j]}")
 print(f"profit:{profit[i,j]}")

store:Bengaluru
category:Electronics
profit:210000
store:Hyderabad
category:Electronics
profit:190000
store:Chennai
category:Electronics
profit:220000
store:Mumbai
category:Electronics
profit:260000
store:Pune
category:Electronics
profit:160000


In [ ]:
#Question 44: Moderate Sales Range
#Find sales values between ₹2,50,000 and ₹5,00,000.
sales_data
moderate_sales=np.logical_and(sales_data>=250000,sales_data<=500000)
store_index,category_index=np.where(moderate_sales)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"moderate_sales:{sales_data[i,j]}")
  print("-"*15)


store:Bengaluru
category:Groceries
moderate_sales:420000
---------------
store:Bengaluru
category:Clothing
moderate_sales:310000
---------------
store:Bengaluru
category:Furniture
moderate_sales:275000
---------------
store:Hyderabad
category:Groceries
moderate_sales:460000
---------------
store:Hyderabad
category:Clothing
moderate_sales:295000
---------------
store:Hyderabad
category:Furniture
moderate_sales:310000
---------------
store:Chennai
category:Groceries
moderate_sales:390000
---------------
store:Chennai
category:Clothing
moderate_sales:340000
---------------
store:Chennai
category:Furniture
moderate_sales:260000
---------------
store:Mumbai
category:Clothing
moderate_sales:375000
---------------
store:Mumbai
category:Furniture
moderate_sales:345000
---------------
store:Mumbai
category:Beauty
moderate_sales:250000
---------------
store:Mumbai
category:Sports
moderate_sales:290000
---------------
store:Pune
category:Groceries
moderate_sales:405000
---------------
store:Pune


In [ ]:
#Question 45: Premium Performance
#A store-category combination is considered premium when:

#Sales are greater than ₹5,00,000
#Profit is greater than ₹1,50,000
profit=sales_data-cost_data
premium_profit_sales=np.logical_and(sales_data > 500000, profit > 150000)
store_index,category_index=np.where(premium_profit_sales)
for i,j in zip(store_index,category_index):
 print(f"store:{stores[i]}")
 print(f"category:{categories[j]}")
 print(f"sales : {sales_data[i,j]}")
 print(f"profit :{profit[i,j]}")
 print("-"*15)

store:Bengaluru
category:Electronics
sales : 850000
profit :210000
---------------
store:Hyderabad
category:Electronics
sales : 780000
profit :190000
---------------
store:Chennai
category:Electronics
sales : 920000
profit :220000
---------------
store:Mumbai
category:Electronics
sales : 1050000
profit :260000
---------------
store:Pune
category:Electronics
sales : 690000
profit :160000
---------------


In [ ]:
#Question 46: Underperforming Combinations
#A store-category combination is considered underperforming when:

#Sales are below ₹2,50,000
#Profit margin is below 25%
#Find all such combinations.
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
total_profit_margin=np.logical_and(profit_margin<25, sales_data<250000)
store_index,category_index=np.where(total_profit_margin)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"sales:{sales_data[i,j]}")
  print(f"profit_margin : {round(profit_margin[i,j],2)}")
  print("-"*20)


store:Pune
category:Furniture
sales:225000
profit_margin : 24.44
--------------------


In [ ]:
#Question 47: Category Performance Classification
#Create a new array that classifies every sales value as:

#"High" when sales are at least ₹5,00,000
#"Medium" when sales are between ₹2,50,000 and ₹4,99,999
#"Low" when sales are below ₹2,50,000
conditions=[
    sales_data<=500000,
    np.logical_and(sales_data >=250000,sales_data<=499999)
]
choices=["High","Medium"]
performance_class=np.select(conditions,choices,default="Low")
print("performance classification array:")
store_index,category_index=np.where(performance_class)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"{performance_class[i][j]}")
  print(f"sales:{sales_data[i,j]}")
  print("-"*30)

performance classification array:
store:Bengaluru
category:Electronics
Low
sales:850000
------------------------------
store:Bengaluru
category:Groceries
High
sales:420000
------------------------------
store:Bengaluru
category:Clothing
High
sales:310000
------------------------------
store:Bengaluru
category:Furniture
High
sales:275000
------------------------------
store:Bengaluru
category:Beauty
High
sales:190000
------------------------------
store:Bengaluru
category:Sports
High
sales:225000
------------------------------
store:Hyderabad
category:Electronics
Low
sales:780000
------------------------------
store:Hyderabad
category:Groceries
High
sales:460000
------------------------------
store:Hyderabad
category:Clothing
High
sales:295000
------------------------------
store:Hyderabad
category:Furniture
High
sales:310000
------------------------------
store:Hyderabad
category:Beauty
High
sales:210000
------------------------------
store:Hyderabad
category:Sports
High
sales:240000
-

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [ ]:
#Question 48: Target Comparison
#Compare every store’s category sales against sales_targets.

#Use NumPy broadcasting.
target_comparsion=sales_data >= sales_targets
difference=sales_data-sales_targets
store_index,category_index=np.where(difference)
for i,j in zip(store_index,category_index):
  status="Achieved" if target_comparsion[i,j] else "Not Achieved"
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"sales:{sales_data[i,j]}")
  print(f'target:{sales_targets[i]}')
  print(f"differnce:{difference[i,j]}")
  print(f"status:{status}")
  print("="*30)

store:Bengaluru
category:Electronics
sales:850000
target:800000
differnce:50000
status:Achieved
store:Bengaluru
category:Groceries
sales:420000
target:800000
differnce:-30000
status:Not Achieved
store:Bengaluru
category:Clothing
sales:310000
target:800000
differnce:-10000
status:Not Achieved
store:Bengaluru
category:Furniture
sales:275000
target:800000
differnce:-25000
status:Not Achieved
store:Bengaluru
category:Beauty
sales:190000
target:800000
differnce:-10000
status:Not Achieved
store:Bengaluru
category:Sports
sales:225000
target:800000
differnce:-5000
status:Not Achieved
store:Hyderabad
category:Electronics
sales:780000
target:450000
differnce:-20000
status:Not Achieved
store:Hyderabad
category:Groceries
sales:460000
target:450000
differnce:10000
status:Achieved
store:Hyderabad
category:Clothing
sales:295000
target:450000
differnce:-25000
status:Not Achieved
store:Hyderabad
category:Furniture
sales:310000
target:450000
differnce:10000
status:Achieved
store:Hyderabad
category:Beaut

In [ ]:
#Question 49: Target Achievement Matrix
#Create a Boolean array where:

#True means the store achieved the category target
#False means the store failed to achieve the target
achievement_matrix=sales_data >= sales_targets
store_index,category_index=np.where(achievement_matrix)
for i in range(len(stores)):
  for j in range(len(categories)):
    print(f"store:{stores[i]}")
    print(f"category:{categories[j]}")
    print(f"{achievement_matrix[i,j]}")
    print("="*30)


store:Bengaluru
category:Electronics
True
store:Bengaluru
category:Groceries
False
store:Bengaluru
category:Clothing
False
store:Bengaluru
category:Furniture
False
store:Bengaluru
category:Beauty
False
store:Bengaluru
category:Sports
False
store:Hyderabad
category:Electronics
False
store:Hyderabad
category:Groceries
True
store:Hyderabad
category:Clothing
False
store:Hyderabad
category:Furniture
True
store:Hyderabad
category:Beauty
True
store:Hyderabad
category:Sports
True
store:Chennai
category:Electronics
True
store:Chennai
category:Groceries
False
store:Chennai
category:Clothing
True
store:Chennai
category:Furniture
False
store:Chennai
category:Beauty
False
store:Chennai
category:Sports
False
store:Mumbai
category:Electronics
True
store:Mumbai
category:Groceries
True
store:Mumbai
category:Clothing
True
store:Mumbai
category:Furniture
True
store:Mumbai
category:Beauty
True
store:Mumbai
category:Sports
True
store:Pune
category:Electronics
False
store:Pune
category:Groceries
False
store

In [ ]:
#Question 50: Target Achievement Count
#Calculate the number of categories in which each store achieved its target.
achievement_count=sales_data >= sales_targets
target_count=np.sum(achievement_count,axis=1)
for i in range (len(stores)):
  print(f"store:{stores[i]}")
  print(f"categories_achieved : {target_count[i]}")
  print("="*30)

store:Bengaluru
categories_achieved : 1
store:Hyderabad
categories_achieved : 4
store:Chennai
categories_achieved : 2
store:Mumbai
categories_achieved : 6
store:Pune
categories_achieved : 0


In [ ]:
#Question 51: Best Target-Performing Store
#Find the store that achieved the highest number of category targets.
from functools import reduce
store_performance=sales_data>=sales_targets
target_achieved_store=np.sum(store_performance,axis=1)
best_store_index=np.argmax(target_achieved_store)
store_name=stores[best_store_index]
highest_target_achieved=target_achieved_store[best_store_index]
print(f"{store_name} store  has achieved the highest category  targets ")




Mumbai store  has achieved the highest category  targets 


In [ ]:
#Question 52: Target Achievement by Category
#Calculate how many stores achieved the target for each product category.
target= sales_data >= sales_targets
target_achievement=np.sum(target,axis=0)
best_category_index=np.argmax(target_achievement)
category_name=categories[best_category_index]
highest_target_category=target_achievement[best_category_index]
print(f"{category_name} prodcut has achieved highest target")

Electronics prodcut has achieved highest target3


In [ ]:
#Question 53: Sales Target Variance
#Calculate the difference between actual sales and target sales for every store.
variance= sales_data-sales_targets
store_index,category_index=np.where(variance)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"sales : {sales_data[i,j]}")
  print(f"target : {sales_targets[j]}")
  print(f"differnce:{variance[i,j]}")
  print("="*30)



store:Bengaluru
category:Electronics
sales : 850000
target : 800000
differnce:50000
store:Bengaluru
category:Groceries
sales : 420000
target : 450000
differnce:-30000
store:Bengaluru
category:Clothing
sales : 310000
target : 320000
differnce:-10000
store:Bengaluru
category:Furniture
sales : 275000
target : 300000
differnce:-25000
store:Bengaluru
category:Beauty
sales : 190000
target : 200000
differnce:-10000
store:Bengaluru
category:Sports
sales : 225000
target : 230000
differnce:-5000
store:Hyderabad
category:Electronics
sales : 780000
target : 800000
differnce:-20000
store:Hyderabad
category:Groceries
sales : 460000
target : 450000
differnce:10000
store:Hyderabad
category:Clothing
sales : 295000
target : 320000
differnce:-25000
store:Hyderabad
category:Furniture
sales : 310000
target : 300000
differnce:10000
store:Hyderabad
category:Beauty
sales : 210000
target : 200000
differnce:10000
store:Hyderabad
category:Sports
sales : 240000
target : 230000
differnce:10000
store:Chennai
catego

In [ ]:
#Question 54: Percentage Above or Below Target
#Calculate the percentage variance from the target using:
variance=sales_data-sales_targets
percentage_variance=(variance/sales_targets)*100
store_index,category_index=np.where(percentage_variance)
for i,j in zip(store_index,category_index):
  if percentage_variance[i,j] >=0:
    status=f"{round(percentage_variance[i,j],2)} above target"
  else:
    status=f"{percentage_variance[i,j]:.2f} below target"
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"status: {status}")
  print("="*30)



store:Bengaluru
category:Electronics
status: 6.25 above target
store:Bengaluru
category:Groceries
status: -6.67 below target
store:Bengaluru
category:Clothing
status: -3.12 below target
store:Bengaluru
category:Furniture
status: -8.33 below target
store:Bengaluru
category:Beauty
status: -5.00 below target
store:Bengaluru
category:Sports
status: -2.17 below target
store:Hyderabad
category:Electronics
status: -2.50 below target
store:Hyderabad
category:Groceries
status: 2.22 above target
store:Hyderabad
category:Clothing
status: -7.81 below target
store:Hyderabad
category:Furniture
status: 3.33 above target
store:Hyderabad
category:Beauty
status: 5.0 above target
store:Hyderabad
category:Sports
status: 4.35 above target
store:Chennai
category:Electronics
status: 15.0 above target
store:Chennai
category:Groceries
status: -13.33 below target
store:Chennai
category:Clothing
status: 6.25 above target
store:Chennai
category:Furniture
status: -13.33 below target
store:Chennai
category:Beauty
s

In [ ]:
#Question 55: Stores Missing Electronics Target
#Identify stores that failed to achieve the Electronics sales target.
electronics_index=np.where(categories=="Electronics")[0][0]
electronics_target=sales_targets[electronics_index]
electronics_sales=sales_data[electronics_index]
for i in range (len(stores)):
  current_electronics_sales=electronics_sales[i]
  if current_electronics_sales < electronics_target:
    variance=current_electronics_sales - electronics_target
    print(f"store:{stores[i]}")
    print(f"sales:{current_electronics_sales}")
    print(f"target:{electronics_target}")
    print(f"missed by:{variance}")
    print("="*20)



store:Hyderabad
sales:420000
target:800000
missed by:-380000
store:Chennai
sales:310000
target:800000
missed by:-490000
store:Mumbai
sales:275000
target:800000
missed by:-525000
store:Pune
sales:190000
target:800000
missed by:-610000


In [ ]:
#Question 56: Stores Achieving All Targets
#Check whether any store achieved its target in all six product categories.
stores_index=sales_data>=sales_targets
store_achieved_targets=np.all(stores_index,axis=1)
store_name=np.where(store_achieved_targets)[0]
for i in range(len(stores)):
  if store_achieved_targets[i]:
   print(f"{stores[i]} achieved all targets")


Mumbai achieved all targets


In [ ]:
#Question 57: Stores Achieving At Least One Target
#Identify stores that achieved at least one category target.
store_index=sales_data >= sales_targets
one_target_store=np.any(store_index,axis=1)
store_name=np.where(one_target_store)
for i in range(len(stores)):
  if one_target_store[i]:
    print(f"{stores[i]} met targets")



Bengaluru met targets
Hyderabad met targets
Chennai met targets
Mumbai met targets


In [ ]:
import numpy as np
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
  ])

In [ ]:
#Question 58: Discount Amount Matrix
#Calculate the discount amount for each store-category combination.

#Use broadcasting.
amount=sales_data*discount_rates
store_index,category_index=np.where(amount)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"{amount[i,j]}")
  print("="*30)

store:Bengaluru
category:Electronics
85000.0
store:Bengaluru
category:Groceries
21000.0
store:Bengaluru
category:Clothing
46500.0
store:Bengaluru
category:Furniture
33000.0
store:Bengaluru
category:Beauty
15200.0
store:Bengaluru
category:Sports
22500.0
store:Hyderabad
category:Electronics
78000.0
store:Hyderabad
category:Groceries
23000.0
store:Hyderabad
category:Clothing
44250.0
store:Hyderabad
category:Furniture
37200.0
store:Hyderabad
category:Beauty
16800.0
store:Hyderabad
category:Sports
24000.0
store:Chennai
category:Electronics
92000.0
store:Chennai
category:Groceries
19500.0
store:Chennai
category:Clothing
51000.0
store:Chennai
category:Furniture
31200.0
store:Chennai
category:Beauty
14800.0
store:Chennai
category:Sports
21500.0
store:Mumbai
category:Electronics
105000.0
store:Mumbai
category:Groceries
25500.0
store:Mumbai
category:Clothing
56250.0
store:Mumbai
category:Furniture
41400.0
store:Mumbai
category:Beauty
20000.0
store:Mumbai
category:Sports
29000.0
store:Pune
catego

In [ ]:
#Question 59: Sales After Discount
#Calculate the net sales value after applying the category-wise discounts.
discount_amount=sales_data*discount_rates
net_sales=sales_data-discount_amount
print("net_sales after discount")
print("="*30)
print(np.round(net_sales,2))
for i in range (len(stores)):
  total_net_sales=np.sum(net_sales[i])
  print(f"{stores[i]} : Total net sales: {total_net_sales:.2f}")
for j in range(len(categories)):
  print(f"{categories[j]:{net_sales[i,j]:.2f}}")


net_sales after discount
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]
Bengaluru : Total net sales: 2046800.00
Hyderabad : Total net sales: 2071750.00
Chennai : Total net sales: 2080000.00
Mumbai : Total net sales: 2542850.00
Pune : Total net sales: 1787250.00
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

In [ ]:
#Question 60: Profit After Discount
#Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
discount_amount=sales_data*discount_rates
net_sales=sales_data-discount_amount
profit_after_discount=net_sales-cost_data
print(np.round(profit_after_discount,2))
for i in range(len(stores)):
  total_profit = np.sum(profit_after_discount[i])
  print(f"{stores[i]} : {total_profit}")


[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]
Bengaluru : 381800.0
Hyderabad : 386750.0
Chennai : 370000.0
Mumbai : 477850.0
Pune : 312250.0


In [ ]:
#Question 61: Profit Margin After Discount
#Calculate the new profit margin after applying discounts.
discount_amount=sales_data*discount_rates
net_sales= sales_data-discount_amount
profit_margin=net_sales - cost_data
new_profit=((profit_margin/net_sales)*100)
store_index,categories_index=np.where(profit_margin)
for i,j in zip(store_index,categories_index):
  print(f"store:{stores[i]} : category:{categories[j]} : profit_margin:{round(new_profit[i,j],2)} ")



store:Bengaluru : category:Electronics : profit_margin:16.34 
store:Bengaluru : category:Groceries : profit_margin:21.05 
store:Bengaluru : category:Clothing : profit_margin:16.51 
store:Bengaluru : category:Furniture : profit_margin:15.29 
store:Bengaluru : category:Beauty : profit_margin:28.49 
store:Bengaluru : category:Sports : profit_margin:20.99 
store:Hyderabad : category:Electronics : profit_margin:15.95 
store:Hyderabad : category:Groceries : profit_margin:19.91 
store:Hyderabad : category:Clothing : profit_margin:16.25 
store:Hyderabad : category:Furniture : profit_margin:17.52 
store:Hyderabad : category:Beauty : profit_margin:27.54 
store:Hyderabad : category:Sports : profit_margin:21.3 
store:Chennai : category:Electronics : profit_margin:15.46 
store:Chennai : category:Groceries : profit_margin:20.38 
store:Chennai : category:Clothing : profit_margin:15.22 
store:Chennai : category:Furniture : profit_margin:14.77 
store:Chennai : category:Beauty : profit_margin:29.49 
sto

In [ ]:
#Question 62: Loss-Making Transactions
#Check whether any store-category combination becomes loss-making after discounts.

#Display the affected store and category names.
discount_amount=sales_data*discount_rates
net_sales=sales_data-discount_amount
trasactions=net_sales-cost_data
loss_trasactions=trasactions<0
store_index,category_index=np.where(loss_trasactions)
for i,j in zip(store_index,category_index):
  print(f"store:{stores[i]}")
  print(f"category:{categories[j]}")
  print(f"loss_trasactions:{loss_trasactions[i,j]}")
if (loss_trasactions[i,j])==0:
  print("good_news no loss_trasactions")
else:
  print(f"loss of trasactions")





good_news no loss_trasactions


In [ ]:
#Question 63: Discount Impact
#Calculate how much total revenue the company loses because of the proposed discounts.
discount_amount=sales_data*discount_rates
total_revenue_lost=np.sum(discount_amount)

print(f"total revenue loss is :{total_revenue_lost}")


total revenue loss is :1146350.0


In [ ]:
#Question 64: Store Most Affected by Discounts
#Identify the store that loses the highest amount of revenue due to discounts.
discount_amount=sales_data*discount_rates
loss_store=np.sum(discount_amount,axis=1)
discount_loss_store=np.argmax(loss_store)
store_name=stores[discount_loss_store]
total_loss=loss_store[discount_loss_store]
print(f"{store_name} is highest loss store {total_loss}")

Mumbai is highest loss store 277150.0


In [ ]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [ ]:
#Question 65: Tax Collection Matrix
#Calculate the tax collected on sales for each store and category.
tax_collection=sales_data*tax_rates
stores_index,category_index=np.where(tax_collection)
for i,j in zip (stores_index,categories_index):
  print(f"store:{stores[i]} and category:{categories[j]}")
  print(f"tax rate = {tax_collection[i,j]}")

store:Bengaluru and category:Electronics
tax rate = 153000.0
store:Bengaluru and category:Groceries
tax rate = 21000.0
store:Bengaluru and category:Clothing
tax rate = 37200.0
store:Bengaluru and category:Furniture
tax rate = 49500.0
store:Bengaluru and category:Beauty
tax rate = 34200.0
store:Bengaluru and category:Sports
tax rate = 27000.0
store:Hyderabad and category:Electronics
tax rate = 140400.0
store:Hyderabad and category:Groceries
tax rate = 23000.0
store:Hyderabad and category:Clothing
tax rate = 35400.0
store:Hyderabad and category:Furniture
tax rate = 55800.0
store:Hyderabad and category:Beauty
tax rate = 37800.0
store:Hyderabad and category:Sports
tax rate = 28800.0
store:Chennai and category:Electronics
tax rate = 165600.0
store:Chennai and category:Groceries
tax rate = 19500.0
store:Chennai and category:Clothing
tax rate = 40800.0
store:Chennai and category:Furniture
tax rate = 46800.0
store:Chennai and category:Beauty
tax rate = 33300.0
store:Chennai and category:Sports

In [ ]:
#Question 66: Sales Including Tax
#Calculate the final customer billing value after adding tax.
final_bill=sales_data*(1+tax_rates)
stores_index,category_index=np.where(final_bill)
for i,j in zip (stores_index,category_index):
  print(f"store :{stores[i]} and category:{categories[j]}")
  print(f"final_bill : {round(final_bill[i,j],2)}")
  print("="*39)

store :Bengaluru and category:Electronics
final_bill : 1003000.0
store :Bengaluru and category:Groceries
final_bill : 441000.0
store :Bengaluru and category:Clothing
final_bill : 347200.0
store :Bengaluru and category:Furniture
final_bill : 324500.0
store :Bengaluru and category:Beauty
final_bill : 224200.0
store :Bengaluru and category:Sports
final_bill : 252000.0
store :Hyderabad and category:Electronics
final_bill : 920400.0
store :Hyderabad and category:Groceries
final_bill : 483000.0
store :Hyderabad and category:Clothing
final_bill : 330400.0
store :Hyderabad and category:Furniture
final_bill : 365800.0
store :Hyderabad and category:Beauty
final_bill : 247800.0
store :Hyderabad and category:Sports
final_bill : 268800.0
store :Chennai and category:Electronics
final_bill : 1085600.0
store :Chennai and category:Groceries
final_bill : 409500.0
store :Chennai and category:Clothing
final_bill : 380800.0
store :Chennai and category:Furniture
final_bill : 306800.0
store :Chennai and cate

In [ ]:
#Question 67: Store-Wise Tax Collection
#Calculate the total tax collected by each store.
tax_collection=sales_data*tax_rates
total_tax_collected=np.sum(tax_collection,axis=1)
for i in range (len(stores)):
  print(f"store:{stores[i]} tax collected is {total_tax_collected[i]}")
  print("="*35)




store:Bengaluru tax collected is 321900.0
store:Hyderabad tax collected is 321200.0
store:Chennai tax collected is 331800.0
store:Mumbai tax collected is 401400.0
store:Pune tax collected is 274650.0


In [ ]:
#Question 68: Category-Wise Tax Collection
#Calculate total tax collected for each category.
tax_collection=sales_data*tax_rates
total_tax_collected=np.sum(tax_collection,axis=0)
for i in range (len(categories)):
  print(f"store:{categories[i]} tax collected is {total_tax_collected[i]}")
  print("="*35)

store:Electronics tax collected is 772200.0
store:Groceries tax collected is 109250.0
store:Clothing tax collected is 192000.0
store:Furniture tax collected is 254700.0
store:Beauty tax collected is 181800.0
store:Sports tax collected is 141000.0


In [ ]:
#Question 69: Highest Tax-Contributing Store
#Identify the store that contributes the highest tax amount.
tax_collection=sales_data*tax_rates
high_pay_store=tax_collection.sum(axis=1)
store_index=np.argmax(high_pay_store)
store_name=stores[store_index]
total_tax=high_pay_store[store_index]
print(f"{store_name} is high tax paying store and tax amount is {total_tax}")

Mumbai is high tax paying store and tax amount is 401400.0


In [ ]:
#Question 70: Updated Pune Electronics Sales
#The Pune store reports that its Electronics sales were entered incorrectly.

#Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.
#Make the change in a copied array without modifying the original array.
updated_sales=sales_data.copy()
pune_index=np.where(stores=="Pune")[0][0]
electronics_index=np.where(categories=="Electronics")[0][0]
updated_sales[pune_index,electronics_index]=740000
print("original sales",sales_data[pune_index,electronics_index])
print("updated sales",updated_sales[pune_index,electronics_index])


original sales 690000
updated sales 740000


In [ ]:
#Question 71: Revised Beauty Cost
#Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

updated_cost = cost_data.copy()
beauty_category_index = np.where(categories == "Beauty")[0][0]
updated_cost[:, beauty_category_index] = updated_cost[:, beauty_category_index] * (1 - 0.08)

for i in range(len(stores)):
  print(f"Store: {stores[i]}")
  print(f"Original Beauty cost: {cost_data[i, beauty_category_index]:.2f}")
  print(f"Updated Beauty cost: {updated_cost[i, beauty_category_index]:.2f}")
  print("="*35)

Store: Bengaluru
Original Beauty cost: 125000.00
Updated Beauty cost: 115000.00
Store: Hyderabad
Original Beauty cost: 140000.00
Updated Beauty cost: 128800.00
Store: Chennai
Original Beauty cost: 120000.00
Updated Beauty cost: 110400.00
Store: Mumbai
Original Beauty cost: 165000.00
Updated Beauty cost: 151800.00
Store: Pune
Original Beauty cost: 115000.00
Updated Beauty cost: 105800.00


In [ ]:
#Question 72: Furniture Cost Increase
#Furniture costs increase by 12% for all stores.

#Update only the Furniture column.
updated_cost = cost_data.copy()
furniture_category_index = np.where(categories == "Furniture")[0][0]
updated_cost[:, furniture_category_index] = updated_cost[:, furniture_category_index] * (1 +0.12)

for i in range(len(stores)):
  print(f"Store: {stores[i]}")
  print(f"Original furniture cost: {cost_data[i, furniture_category_index]:.2f}")
  print(f"Updated furniture cost: {updated_cost[i,furniture_category_index]:.2f}")
  print("="*30)

Store: Bengaluru
Original furniture cost: 205000.00
Updated furniture cost: 229600.00
Store: Hyderabad
Original furniture cost: 225000.00
Updated furniture cost: 252000.00
Store: Chennai
Original furniture cost: 195000.00
Updated furniture cost: 218400.00
Store: Mumbai
Original furniture cost: 250000.00
Updated furniture cost: 280000.00
Store: Pune
Original furniture cost: 170000.00
Updated furniture cost: 190400.00


In [ ]:
#Question 73: Store Closure Simulation
#Assume the Pune store is temporarily closed.

#Remove Pune’s sales and cost data from the analysis using np.delete().
pune_index=np.where(stores=="Pune")[0][0]
updated_stores= np.delete(stores,pune_index,axis=0)
updated_cost=np.delete(cost_data,pune_index,axis=0)
updated_sales=np.delete(sales_data,pune_index,axis=0)
print(f"updated_stores : {updated_stores}")
print(f"updated_cost : {updated_cost}")
print(f"updated_sales : {updated_sales}")



updated_stores : ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
updated_cost : [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]
updated_sales : [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]


In [ ]:
#Question 74: Adding a New Store
#A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

In [ ]:
updated_stores=stores.copy()
updated_stores=np.append(updated_stores,"Delhi")
updated_sales=np.vstack(delhi_sales)
updated_cost=np.vstack(delhi_cost)
print(f"updated stores : {updated_stores}")
print(f"updated_sales : {updated_sales}")
print(f"updated_cost : {updated_cost}")

updated stores : ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
updated_sales : [[880000]
 [475000]
 [330000]
 [290000]
 [215000]
 [250000]]
updated_cost : [[665000]
 [360000]
 [235000]
 [215000]
 [145000]
 [180000]]


In [ ]:
#Question 75: Adding a New Product Category
#SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

In [ ]:
updated_categpry=categories.copy()
updated_category_2=np.append(categories,"home appliances")
updated_sales=np.hstack(home_appliance_sales)
updated_cost=np.hstack(home_appliance_cost)
print(f"updated category : {updated_category_2}")
print(f"updated sales : {updated_sales}")
print(f"updated cost : {updated_cost}")

updated category : ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'home appliances']
updated sales : [360000 325000 390000 420000 295000]
updated cost : [265000 240000 285000 305000 225000]


In [ ]:
#Question 76: Sort Stores by Sales
#Sort stores in ascending order based on total sales.

#Display store names and sales totals.
total_sales=np.sum(sales_data,axis=1)
stores_order=list(zip(stores,total_sales))
ascending=sorted(stores_order,key=lambda x:x[1])
for store,sales in ascending:
  print(f"{store} : {sales}")
  print("="*30)

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


In [ ]:
#Question 77: Rank Stores by Profit
#Rank stores from highest to lowest total profit.
profit=sales_data-cost_data
total_profit=np.sum(profit,axis=1)
rank_stores=np.argsort(total_profit)+1
ranked_stores=list(zip(stores,rank_stores))
for store,rank in ranked_stores:
  print(f"{store} : {rank}")



Bengaluru : 5
Hyderabad : 3
Chennai : 1
Mumbai : 2
Pune : 4


In [ ]:
#Question 78: Sort Categories by Revenue
#Sort product categories from highest to lowest total revenue
revnue=np.sum(sales_data,axis=0)
rank_category=np.argsort(revnue)+1
ranked_category=list(zip(categories,rank_category))
for store,rank in ranked_category:
  print(f"{store} : {rank}")

Electronics : 5
Groceries : 6
Clothing : 4
Furniture : 3
Beauty : 2
Sports : 1


In [ ]:
#Question 79: Top Three Store-Category Sales
#Find the three highest individual sales values in the complete sales matrix.

#Display their:

#Sales value
#Store name
#Category name
flat_sales=sales_data.flatten()
sorted_indices= np.argsort(flat_sales)[::-1]
print("Top three individual sales Values")
for i in range (3):
  sales_value = flat_sales[sorted_indices[i]]
  original_index=np.unravel_index(sorted_indices[i],sales_data.shape)
  store_idx,category_index=original_index
  print(f"sales value : {sales_value}")
  print(f"store name : {stores[store_idx]}")
  print(f"category name : {categories[category_index]}")
  print("="*30)



Top three individual sales Values
sales value : 1050000
store name : Mumbai
category name : Electronics
sales value : 920000
store name : Chennai
category name : Electronics
sales value : 850000
store name : Bengaluru
category name : Electronics


In [ ]:
#Question 80: Bottom Three Profits
#Find the three lowest profit values in the profit matrix.
profit=sales_data-cost_data
flat_profit=profit.flatten()
sorted_indices=np.argsort(flat_profit)
for i in range (3):
  least_profit=flat_profit[sorted_indices[i]]
  original_index=np.unravel_index(sorted_indices[i],sales_data.shape)
  store_idx,category_index=original_index
  print(f"bottom_profit : {least_profit}")
  print(f"store name : {stores[store_idx]}")
  print(f"category namr : {categories[category_index]}")
  print("="*30)

bottom_profit : 55000
store name : Pune
category namr : Furniture
bottom_profit : 60000
store name : Pune
category namr : Sports
bottom_profit : 60000
store name : Chennai
category namr : Sports


In [ ]:
#Part 14: Statistical Analysis
#Question 81: Sales Statistics
#Calculate the following for the complete sales array:

#Minimum
#Maximum
#Mean
#Median
#standard deviation
#Variance
#25th percentile
#50th percentile
#75th percentile
min_sales=np.min(sales_data)
max_sales=np.max(sales_data)
mean_sales=np.mean(sales_data)
median_sales=np.median(sales_data)
std_sales=np.std(sales_data)
var_sales=np.var(sales_data)
sales_25=np.percentile(sales_data,25)
sales_50=np.percentile(sales_data,50)
sales_75=np.percentile(sales_data,75)
print(f"min sales : {min_sales}")
print(f'max sales : {max_sales}')
print(f'mean sales : {round(mean_sales,2)}')
print(f"median sales : {round(median_sales,2)}")
print(f"standard deviation {round(std_sales,2)}")
print(f"variance : {round(var_sales,2)}")
print(f"sales_25 : {sales_25}")
print(f"sales_50 : {sales_50}")
print(f"sales_75 : {sales_75}")

min sales : 175000
max sales : 1050000
mean sales : 389166.67
median sales : 302500.0
standard deviation 230322.54
variance : 53048472222.22
sales_25 : 228750.0
sales_50 : 302500.0
sales_75 : 416250.0


In [ ]:
#Question 82: Store-Wise Standard Deviation
#Calculate the sales standard deviation for every store.

#Use this value to determine which store has the most variation between product categories.
std_sales=np.std(sales_data,axis=1)
store_index=np.argmax(std_sales)
store_name=stores[store_index]
variation_std=std_sales[store_index]
print(f"store name : {store_name}")
print(f"standard deviation of store : {variation_std:.2f}")

store name : Mumbai
standard deviation of store : 271860.87


In [ ]:
#Question 83: Category-Wise Standard Deviation
#Determine which product category has the highest variation in sales across stores.
sales_std=np.std(sales_data,axis=0)
category_index=np.argmax(sales_std)
category_name=categories[category_index]
variation_std=sales_std[category_index]
print(f"category_name : {category_name}")
print(f"std deviation of category : {variation_std:.2f}")

category_name : Electronics
std deviation of category : 122539.79


In [ ]:
#Question 84: Sales Above Company Average
#Calculate the company-wide average sales value.

#Count how many store-category sales values are above this average.
company_avg=np.average(sales_data)
avg_sales_comp=(sales_data > company_avg)
store_index,category_index=np.where(avg_sales_comp)
print(f"company avg :{round(company_avg,2)}")
for i,j in zip(store_index,category_index):
  print(f"="*30)
  print(f"store : {stores[i]}")
  print(f"category: {categories[j]}")
  print(f"{avg_sales_comp[i,j]}")

company avg :389166.67
store : Bengaluru
category: Electronics
True
store : Bengaluru
category: Groceries
True
store : Hyderabad
category: Electronics
True
store : Hyderabad
category: Groceries
True
store : Chennai
category: Electronics
True
store : Chennai
category: Groceries
True
store : Mumbai
category: Electronics
True
store : Mumbai
category: Groceries
True
store : Pune
category: Electronics
True
store : Pune
category: Groceries
True


In [ ]:
#Question 85: Outlier Detection
#Treat any sales value greater than:
mean_sales=np.mean(sales_data)
std_dev_sales=np.std(sales_data)
outlier_detect=mean_sales+1.5 * std_dev_sales
print(f"Outlier detection : {outlier_detect:.2f}")


Outlier detection : 734650.48


In [ ]:
#Part 15: Reshaping and Transformation
#Question 86: Flatten Sales Data
#Convert the two-dimensional sales array into a one-dimensional array using:

#flatten()
#ravel()
#Explain the difference between the two methods.
sales=sales_data.flatten()
convert_array=sales.ravel()
print(f"using ravel :{convert_array}")
print(f" using flatten:{sales}")

using ravel :[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
 using flatten:[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [ ]:
#Question 87: Reshape Sales Data
#Reshape the 5 × 6 sales array into:

#3 × 10
#10 × 3
#2 × 15
#15 × 2
#Verify that no data is lost.
data_3_10=sales_data.reshape(3,10)
print(f"{data_3_10} total elemnts {data_3_10.size}")

data_10_3=sales_data.reshape(10,3)
print(f"{data_10_3} total elemnts {data_10_3.size}")
data_2_15=sales_data.reshape(2,15)
print(f"{data_2_15} total elemnts {data_2_15.size}")
data_15_2=sales_data.reshape(15,2)
print(f"{data_15_2} total elemnts {data_15_2.size}")

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]] total elemnts 30
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]] total elemnts 30
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]] total elemnts 30
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]


In [ ]:
#Question 88: Transpose Sales Data
#Transpose the sales array so that:

#Rows represent product categories
#Columns represent stores
represnt_sales_data=sales_data.T
print(f"{represnt_sales_data}")

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


In [ ]:
#Question 89: Combined Sales and Cost Array
#Stack sales_data and cost_data vertically.
sales_data=np.vstack(sales_data)
cost_data=np.vstack(cost_data)
np.concatenate([sales_data,cost_data])

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000],
       [ 640000,  315000,  220000,  205000,  125000,  160000],
       [ 590000,  350000,  210000,  225000,  140000,  170000],
       [ 700000,  295000,  245000,  195000,  120000,  155000],
       [ 790000,  390000,  265000,  250000,  165000,  205000],
       [ 530000,  310000,  205000,  170000,  115000,  145000]])

In [ ]:
#Question 90: Store-Level Combined Data
#Create a three-dimensional array where:
#First layer contains sales data
#Second layer contains cost data
combine_3d=np.stack([sales_data,cost_data])
print(combine_3d)
print(f"size of array is : {combine_3d.shape}")

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
size of array is : (2, 5, 6)


In [ ]:
import numpy as np
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [ ]:
import numpy as np
stores=["storeA","storeB","storeC","storeD","storeE"]
categories=["electronics","toys","food","cloth","groceries"]
total_missing=np.isnan(sales_with_missing).sum()
print("1. total missing values:",total_missing)
row_index,col_index=np.where(np.isnan(sales_with_missing))
print("\n 2. location of missing values:")
for r,c in zip(row_index,col_index):
  print(f"{stores[r]} , {categories[c]} at position [{r},{c}]")
stores_with_nan=np.unique(row_index)
print("\n3. stores with missing values:",[stores[i] for i in stores_with_nan])
categories_with_nan=np.unique(col_index)
print("\n4. categories witb missing values:", [categories[i] for i in categories_with_nan ])

1. total missing values: 4

 2. location of missing values:
storeA , food at position [0,2]
storeB , cloth at position [1,3]
storeD , toys at position [3,1]
storeE , groceries at position [4,4]

3. stores with missing values: ['storeA', 'storeB', 'storeD', 'storeE']

4. categories witb missing values: ['toys', 'food', 'cloth', 'groceries']


In [ ]:
#Question 92: Replace Missing Values with Zero
#Replace all missing sales values with zero.
sales_with_missing[np.isnan(sales_with_missing)]=0
print(f"{sales_with_missing}")

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [ ]:
#Question 93: Replace with Company Average
#Replace missing values with the overall average of available sales values.
mean_missing_value= sales_with_missing[sales_with_missing!=0].mean()
sales_with_missing[sales_with_missing==0]=mean_missing_value
print(sales_with_missing)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [ ]:
#Question 94: Replace with Category Average
#Replace each missing value with the average sales value of its respective product category.

# Re-initializing sales_with_missing to its original state with np.nan values
# as defined in cell Aa5byJFLpE0m, for accurate category-wise replacement.
import numpy as np
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

category_avg=np.nanmean(sales_with_missing,axis=0)
for col_index in range(sales_with_missing.shape[1]):
  nan_cat_col=np.isnan(sales_with_missing[:, col_index])
  sales_with_missing[nan_cat_col,col_index]=category_avg[col_index]
print(sales_with_missing)


[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [ ]:
#Question 95: Missing Value Impact
#Compare total sales before and after replacing missing values with zero.
original_value=np.nansum(sales_with_missing)
sales_filled=sales_with_missing.copy()
sales_filled[np.isnan(sales_filled)]=0
total_sales=np.sum(sales_filled)
print(f" sales before zero : {original_value}")
print(f"sales after zero : {total_sales}")

 sales before zero : 10370000.0
sales after zero : 10370000.0


In [ ]:
#Part 17: Conditional Business Decisions
#Question 96: Store Performance Labels
#Classify each store based on total sales:

#"Excellent": Total sales above ₹28,00,000
#"Good": Total sales between ₹24,00,000 and ₹28,00,000
#"Needs Improvement": Total sales below ₹24,00,000
store_total_sales=np.sum(sales_data,axis=1)
conditions=[
    store_total_sales>2800000,
    (store_total_sales>=2400000)&(store_total_sales<=2800000),
    store_total_sales<2400000
]
choices=["Excellent","Good","Needs imporvement"]
store_perf_labels=np.select(conditions,choices,default='check data')
for i in range (len(stores)):
  print(f"store : {stores[i]}")
  print(f"sales :{store_total_sales[i]}")
  print(f"performance :{store_perf_labels[i]}")

store : Bengaluru
sales :2270000
performance :Needs imporvement
store : Hyderabad
sales :2295000
performance :Needs imporvement
store : Chennai
sales :2310000
performance :Needs imporvement
store : Mumbai
sales :2820000
performance :Excellent
store : Pune
sales :1980000
performance :Needs imporvement


In [ ]:
#Question 97: Profitability Classification
#Classify each store-category combination as:

#"Highly Profitable": Profit above ₹2,00,000
#"Profitable": Profit between ₹1,00,000 and ₹2,00,000
#"Low Profit": Profit below ₹1,00,000
#"Loss": Profit below zero
profit=sales_data-cost_data
conditions=[
    profit<0,
    profit<100000,
    (profit>=100000)&(profit<=200000),
    profit>200000
]
choices=["Loss","Low profit","Profitable","Highly profitable"]
profit_classification=np.select(conditions,choices,default="check data")
for i in range(len(stores)):
  for j in range(len(categories)):
    print(f"store:{stores[i]}")
    print(f"category:{categories[j]}")
    print(f"profit : {profit[i,j]}")
    print(f"classification : {profit_classification[i,j]}")
    print("="*30)


store:Bengaluru
category:Electronics
profit : 210000
classification : Highly profitable
store:Bengaluru
category:Groceries
profit : 105000
classification : Profitable
store:Bengaluru
category:Clothing
profit : 90000
classification : Low profit
store:Bengaluru
category:Furniture
profit : 70000
classification : Low profit
store:Bengaluru
category:Beauty
profit : 65000
classification : Low profit
store:Bengaluru
category:Sports
profit : 65000
classification : Low profit
store:Hyderabad
category:Electronics
profit : 190000
classification : Profitable
store:Hyderabad
category:Groceries
profit : 110000
classification : Profitable
store:Hyderabad
category:Clothing
profit : 85000
classification : Low profit
store:Hyderabad
category:Furniture
profit : 85000
classification : Low profit
store:Hyderabad
category:Beauty
profit : 70000
classification : Low profit
store:Hyderabad
category:Sports
profit : 70000
classification : Low profit
store:Chennai
category:Electronics
profit : 220000
classificati

In [ ]:
#Question 98: Expansion Recommendation
#A store is eligible for expansion when:

#Total sales are above ₹25,00,000
#Total profit is above ₹7,00,000
#Overall profit margin is above 25%
store_sales=np.sum(sales_data,axis=1)
profit=sales_data-cost_data
total_profit=np.sum(profit,axis=1)
profit_margin=(total_profit/store_sales)
conditions=(
    (store_sales>2500000)&
    (total_profit>700000)&
    (profit_margin>25)
)
expansion_elgible=np.where(conditions,"store is elgible for expansion","Not elgible")
for i in range (len(stores)):
  print(f"store : {stores[i]}")
  print(f"elgible for expansion : {expansion_elgible[i]}")

store : Bengaluru
elgible for expansion : Not elgible
store : Hyderabad
elgible for expansion : Not elgible
store : Chennai
elgible for expansion : Not elgible
store : Mumbai
elgible for expansion : Not elgible
store : Pune
elgible for expansion : Not elgible


In [ ]:
#Question 99: Category Promotion Recommendation
#A product category should receive additional promotion when:

#Average sales are below ₹3,00,000
#Profit margin is above 25%
#Identify the categories that satisfy these conditions.
profit=sales_data-cost_data
total_profit=np.sum(profit,axis=0)
total_sales=np.sum(sales_data,axis=0)
profit_margin=(total_profit/total_sales)*100
avg_sales=np.mean(sales_data,axis=0)

conditions=[
    profit_margin>25,
    avg_sales<300000
]
combined_condn=np.logical_and.reduce(conditions)
promotion_rec=np.where(combined_condn,"category is elgible for promotion","Not elgible")
for i in range (len(categories)):
  print(f"category : {categories[i]}")
  print(f"promotion : {promotion_rec[i]}")
  print(f"="*30)


category : Electronics
promotion : Not elgible
category : Groceries
promotion : Not elgible
category : Clothing
promotion : Not elgible
category : Furniture
promotion : category is elgible for promotion
category : Beauty
promotion : category is elgible for promotion
category : Sports
promotion : category is elgible for promotion


In [ ]:
#Question 100: Cost Optimization Recommendation
#Find store-category combinations where:

#Cost is greater than ₹2,50,000
#Profit margin is below 25%
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
conditions=(
    (cost_data>250000)&
    (profit_margin<25)

)
cost_optimization=np.where(conditions," elgible for cost optimization","Not eligible")
for i in range (len(stores)):
  for j in range (len(categories)):
    print(f"store : {stores[i]}")
    print(f"catgeory : {categories[j]}")
    print(f"cost_data : {cost_data[i,j]}")
    print(f"profit_margin ; {profit_margin[i,j]:.2f}")
    print(f"cost optimization check :{cost_optimization[i,j]}")
    print("="*30)

store : Bengaluru
catgeory : Electronics
cost_data : 640000
profit_margin ; 24.71
cost optimization check : elgible for cost optimization
store : Bengaluru
catgeory : Groceries
cost_data : 315000
profit_margin ; 25.00
cost optimization check :Not eligible
store : Bengaluru
catgeory : Clothing
cost_data : 220000
profit_margin ; 29.03
cost optimization check :Not eligible
store : Bengaluru
catgeory : Furniture
cost_data : 205000
profit_margin ; 25.45
cost optimization check :Not eligible
store : Bengaluru
catgeory : Beauty
cost_data : 125000
profit_margin ; 34.21
cost optimization check :Not eligible
store : Bengaluru
catgeory : Sports
cost_data : 160000
profit_margin ; 28.89
cost optimization check :Not eligible
store : Hyderabad
catgeory : Electronics
cost_data : 590000
profit_margin ; 24.36
cost optimization check : elgible for cost optimization
store : Hyderabad
catgeory : Groceries
cost_data : 350000
profit_margin ; 23.91
cost optimization check : elgible for cost optimization
store

In [ ]:
#Part 18: Inventory Scenario
#Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [ ]:
#Question 101: Closing Stock
#Calculate closing stock using:
closing_stock=(opening_stock-units_sold)
print(f"{closing_stock}")

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [ ]:
#Question 102: Low-Stock Identification
#Identify store-category combinations where closing stock is below 30 units.
closing_stock=opening_stock-units_sold
stock=closing_stock<30
store,category=np.where(closing_stock)
for i,j in zip(store,category):
  print(f"store : {stores[i]}")
  print(f'category : {categories[j]}')
  print(f"closing stock : {stock[i,j]}")
  print(f"stock : {closing_stock[i,j]}")
  print("="*30)

store : Bengaluru
category : Electronics
closing stock : True
stock : 25
store : Bengaluru
category : Groceries
closing stock : False
stock : 70
store : Bengaluru
category : Clothing
closing stock : False
stock : 60
store : Bengaluru
category : Furniture
closing stock : True
stock : 25
store : Bengaluru
category : Beauty
closing stock : False
stock : 60
store : Bengaluru
category : Sports
closing stock : False
stock : 40
store : Hyderabad
category : Electronics
closing stock : True
stock : 25
store : Hyderabad
category : Groceries
closing stock : False
stock : 80
store : Hyderabad
category : Clothing
closing stock : False
stock : 50
store : Hyderabad
category : Furniture
closing stock : True
stock : 25
store : Hyderabad
category : Beauty
closing stock : False
stock : 60
store : Hyderabad
category : Sports
closing stock : False
stock : 45
store : Chennai
category : Electronics
closing stock : True
stock : 25
store : Chennai
category : Groceries
closing stock : False
stock : 70
store : C

In [ ]:
#Question 103: Stock Availability Percentage
#Calculate the percentage of opening stock that remains unsold.
stock_percentage=(closing_stock/opening_stock)*100
print(f"{np.round(stock_percentage,2)}")


[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [ ]:
#Question 104: Fast-Moving Products
#A product is considered fast-moving when more than 80% of its opening stock has been sold.

#Identify fast-moving store-category combinations.
fast_moving=(units_sold/opening_stock)*100
stock=fast_moving>80
store_index,category_index=np.where(stock)
for i,j in zip(store_index,category_index):
  print(f"{stores[i]} and category {categories[j]} and percentage {stock[i,j]}")
  print(f"{np.round(fast_moving[i,j],2)}")


Bengaluru and category Groceries and percentage True
84.44
Hyderabad and category Groceries and percentage True
84.0
Hyderabad and category Clothing and percentage True
82.14
Chennai and category Electronics and percentage True
80.77
Chennai and category Groceries and percentage True
83.33
Chennai and category Clothing and percentage True
84.38
Mumbai and category Electronics and percentage True
83.33
Mumbai and category Groceries and percentage True
85.45
Mumbai and category Clothing and percentage True
84.29
Pune and category Groceries and percentage True
82.5


In [ ]:
#Question 105: Category-Wise Units Sold
#Calculate the total units sold for each product category.
sold=np.sum(units_sold,axis=0)
for i in range (len(categories)):
  print(f"category : {categories[i]} and sold units are : {sold[i]}")


category : Electronics and sold units are : 485
category : Groceries and sold units are : 1950
category : Clothing and sold units are : 1240
category : Furniture and sold units are : 345
category : Beauty and sold units are : 980
category : Sports and sold units are : 720


In [ ]:
#Question 106: Store-Wise Units Sold
#Calculate total units sold by each store.
sold=np.sum(units_sold,axis=1)
for i in range (len(stores)):
  print(f"store : {stores[i]} and sold units are : {sold[i]}")


store : Bengaluru and sold units are : 1110
store : Hyderabad and sold units are : 1175
store : Chennai and sold units are : 1095
store : Mumbai and sold units are : 1390
store : Pune and sold units are : 950


In [ ]:
#Question 107: Best Store by Unit Sales
#Identify the store that sold the highest total number of units.
sold=np.sum(units_sold,axis=1)
store_index=np.argmax(sold)
store_name=stores[store_index]
amount=sold[store_index]
print(f"store : {store_name} and sold units are : {amount}")



store : Mumbai and sold units are : 1390


In [ ]:
#Question 108: Reorder Requirement
#A store should reorder a category when closing stock is below 25 units.

#Create a Boolean reorder matrix.
order_require=closing_stock>25
store_name,category_name=np.where(order_require)
for i,j in zip(store_name,category_name):
  print(f"store:{stores[i]}")
  print(f"category : {categories[j]}")
  print(f"Have to order : {order_require[i,j]}")
  print("="*30)

store:Bengaluru
category : Groceries
Have to order : True
store:Bengaluru
category : Clothing
Have to order : True
store:Bengaluru
category : Beauty
Have to order : True
store:Bengaluru
category : Sports
Have to order : True
store:Hyderabad
category : Groceries
Have to order : True
store:Hyderabad
category : Clothing
Have to order : True
store:Hyderabad
category : Beauty
Have to order : True
store:Hyderabad
category : Sports
Have to order : True
store:Chennai
category : Groceries
Have to order : True
store:Chennai
category : Clothing
Have to order : True
store:Chennai
category : Beauty
Have to order : True
store:Chennai
category : Sports
Have to order : True
store:Mumbai
category : Groceries
Have to order : True
store:Mumbai
category : Clothing
Have to order : True
store:Mumbai
category : Furniture
Have to order : True
store:Mumbai
category : Beauty
Have to order : True
store:Mumbai
category : Sports
Have to order : True
store:Pune
category : Groceries
Have to order : True
store:Pune
c

In [ ]:
#Question 109: Reorder Quantity
#Assume each category must maintain 100 units after reordering.
#Calculate reorder quantities only for combinations where closing stock is below 25.
#For all other combinations, return zero.
closing_stock=opening_stock-units_sold
target_qty=100
threshold_qty=25
reorder_qty=np.where(closing_stock<threshold_qty,target_qty-closing_stock,0)
print(reorder_qty)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [ ]:
#Part 19: Advanced NumPy Questions
#Question 110: Cumulative Store Sales
#Calculate cumulative category sales for each store using np.cumsum().
cumulative_store_sales=np.sum(sales_data,axis=1)
for i in range (len(stores)):
  print(f"{stores[i]}:RS.{cumulative_store_sales[i]}")
  print("Total company sales : RS.",np.sum(cumulative_store_sales))


Bengaluru:RS.2270000
Total company sales : RS. 11675000
Hyderabad:RS.2295000
Total company sales : RS. 11675000
Chennai:RS.2310000
Total company sales : RS. 11675000
Mumbai:RS.2820000
Total company sales : RS. 11675000
Pune:RS.1980000
Total company sales : RS. 11675000


In [ ]:
#Question 111: Cumulative Company Sales
#Flatten the sales array and calculate cumulative company sales.
cumulative_company_sales=np.sum(sales_data)
print(f"Total cumulative company sales: RS.{cumulative_company_sales}")

Total cumulative company sales: RS.11675000


In [ ]:
#Question 112: Sales Difference Between Categories
#Calculate the difference between consecutive category sales for each store using np.diff().
sales_cat=np.sum(sales_data,axis=0)
sales_diff=np.diff(sales_cat)
print('Sales difference between consecutive categories:')
print(sales_diff)


Sales difference between consecutive categories:
[-2105000  -585000  -185000  -405000   165000]


In [ ]:
#Question 113: Unique Sales Values
#Find all unique sales values in sales_data.

#Also count the frequency of each value.
sales_value, counts = np.unique(sales_data, return_counts=True)
for val,count in zip(sales_value,counts):
  print(f"This {val} has appeared :{count} times")

This 175000 has appeared :1 times
This 185000 has appeared :1 times
This 190000 has appeared :1 times
This 205000 has appeared :1 times
This 210000 has appeared :1 times
This 215000 has appeared :1 times
This 225000 has appeared :2 times
This 240000 has appeared :1 times
This 250000 has appeared :1 times
This 260000 has appeared :1 times
This 275000 has appeared :1 times
This 280000 has appeared :1 times
This 290000 has appeared :1 times
This 295000 has appeared :1 times
This 310000 has appeared :2 times
This 340000 has appeared :1 times
This 345000 has appeared :1 times
This 375000 has appeared :1 times
This 390000 has appeared :1 times
This 405000 has appeared :1 times
This 420000 has appeared :1 times
This 460000 has appeared :1 times
This 510000 has appeared :1 times
This 690000 has appeared :1 times
This 780000 has appeared :1 times
This 850000 has appeared :1 times
This 920000 has appeared :1 times
This 1050000 has appeared :1 times


In [ ]:
#Question 114: Search for Specific Sales
#Check whether the value ₹4,20,000 exists in the sales array.
#Return its location.
specific_value=420000
location=np.where(sales_data==specific_value)
if location[0].size>0:
  rows,column=location
for i,j in zip(rows,column):
  print(f"The value {specific_value}exists in the sales array at the following locations")
  print(f"store : {stores[i]} , Category:{categories[j]},Index:({i},{j})")

The value 420000exists in the sales array at the following locations
store : Bengaluru , Category:Groceries,Index:(0,1)


In [ ]:
#Question 115: Compare Sales and Cost
#Create a Boolean array showing whether sales are greater than cost for every combination.

#Verify whether all combinations are profitable using np.all()
check=np.all(sales_data>cost_data)
check

np.True_

In [ ]:
#Question 116: Clip Profit Values
#For reporting purposes, management wants profit values limited to:

#Minimum: ₹75,000
#Maximum: ₹2,50,000
profit=sales_data-cost_data
profit_min=75000
profit_max=250000
clipped_profit=np.clip(profit,profit_min,profit_max)
print("original_profit")
print(profit)
print("clipped_profit")
print(clipped_profit)

original_profit
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
clipped_profit
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [ ]:
#Question 117: Normalize Sales Data
#Normalize all sales values using min-max normalization:
min_sales_value=np.min(sales_data)
max_sales_value=np.max(sales_data)
normalize_sales_data=(sales_data-min_sales_value)/(max_sales_value-min_sales_value)
print("Normalize sales Data")
print(np.round(normalize_sales_data,2))

Normalize sales Data
[[0.77 0.28 0.15 0.11 0.02 0.06]
 [0.69 0.33 0.14 0.15 0.04 0.07]
 [0.85 0.25 0.19 0.1  0.01 0.05]
 [1.   0.38 0.23 0.19 0.09 0.13]
 [0.59 0.26 0.12 0.06 0.   0.03]]


In [ ]:
#Question 118: Standardize Sales Data
mean=sales_data.mean()
std=sales_data.std()
standardize_sales=(sales_data-mean)/std
print(f"{np.round(standardize_sales,2)}")

[[ 2.    0.13 -0.34 -0.5  -0.86 -0.71]
 [ 1.7   0.31 -0.41 -0.34 -0.78 -0.65]
 [ 2.3   0.   -0.21 -0.56 -0.89 -0.76]
 [ 2.87  0.52 -0.06 -0.19 -0.6  -0.43]
 [ 1.31  0.07 -0.47 -0.71 -0.93 -0.8 ]]


In [ ]:
#Question 119: Round Values
#Convert profit margin values into:

#Two decimal places
#Nearest whole number
#Floor values
#Ceiling values
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
print("profit margin")
print(f"{np.round(profit_margin,2)}")
print("Nearest whole number")
print(f"{np.round(profit_margin)}")
print("floor values")
print(f"{np.floor(profit_margin)}")
print(f"ceiling values")
print(f"{np.ceil(profit_margin)}")

profit margin
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Nearest whole number
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
floor values
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
ceiling values
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [ ]:
#Question 120: Save and Load Data
#Save the following arrays as NumPy binary files:

#sales_data.npy
#cost_data.npy
#profit_data.npy
#Load them back and verify that the loaded arrays are equal to the original arrays.
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit)
print("Files saved successfully!")
loaded_sales=np.load("sales_data.npy")
loaded_cost=np.load("cost_data.npy")
loaded_profit=np.load("profit_data.npy")
print("\nverification")
print("sales_data_equal?",np.array_equal(sales_data,loaded_sales))
print("cost_data_equal?",np.array_equal(cost_data,loaded_cost))
print("profit_data_equal?",np.array_equal(profit,loaded_profit))

Files saved successfully!

verification
sales_data_equal? True
cost_data_equal? True
profit_data_equal? True


Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder
Expected Final Output Format
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:
Assignment Rules
Use NumPy for all calculations.
Do not manually calculate or hard-code answers.
Avoid Python loops wherever a NumPy vectorized solution is possible.
Use axis-based operations correctly.
Display store and category names along with calculated values.
Round percentage values to two decimal places.
Use Boolean indexing for filtering questions.
Use broadcasting for target, discount, and tax calculations.
Do not modify the original arrays unless specifically instructed.
Add comments explaining the purpose of important calculations.
Submission Requirements
Submit the assignment as a Jupyter Notebook containing:

Business scenario
Dataset creation
Question number and question description
NumPy solution below every question
Output for every solution
Final retail performance report
Minimum five business observations
Minimum three management recommendations


In [ ]:
sales=np.sum(sales_data)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("="*35)
print("\nCOMPANY SUMMARY")
print("-"*15)
print(f"Total Sales: {sales}")
cost=np.sum(cost_data)
print(f"Total Cost: {cost}")
profit=np.sum(sales_data-cost_data)
print(f"Total Profit: {profit}")
profit_margin=(profit/sales_data.sum())*100
print(f"Overall Profit Margin: {np.round(profit_margin,2)}")
print("\nBEST-PERFORMING STORE")
print("-"*21)
store_total_sales_per_store=np.sum(sales_data,axis=1)
store_index=np.argmax(store_total_sales_per_store)
store_name=stores[store_index]
store_sales_data_for_best_store=sales_data[store_index]
store_total_sales=np.sum(store_sales_data_for_best_store)
cost_data_for_best_store=cost_data[store_index]
total_cost_store=np.sum(cost_data_for_best_store)
store_profit=(store_total_sales-total_cost_store)
store_profit_margin=(store_profit/store_total_sales)*100
print(f"Store: {store_name}")
print(f"Sales: {store_total_sales}")
print(f"Cost: {total_cost_store}")
print(f"Profit: {store_profit}")
print(f"Profit Margin: {store_profit_margin:.2f}")
print("\nMOST PROFITABLE CATEGORY")
print("-"*24)
category_total_sales_across_stores=np.sum(sales_data,axis=0)
category_index=np.argmax(category_total_sales_across_stores)
category_name=categories[category_index]
category_sales_for_most_profitable_category=sales_data[:, category_index]
total_category_sales=np.sum(category_sales_for_most_profitable_category)
category_cost_for_most_profitable_category=cost_data[:, category_index]
total_category_cost=np.sum(category_cost_for_most_profitable_category)
category_profit=(total_category_sales-total_category_cost)
category_profit_margin=(category_profit/total_category_sales)*100
print(f"Category: {category_name}")
print(f"Sales: {total_category_sales}")
print(f"Cost: {total_category_cost}")
print(f'Profit:{category_profit}')
print(f"Profit Margin: {category_profit_margin:.2f}")
print("\nEXPANSION RECOMMENDATIONS")
print("-"*25)
store_exp=np.sum(sales_data,axis=1)
profit_exp=sales_data-cost_data
total_profit_exp=np.sum(profit_exp)
profit_margin=(total_profit/store_exp)*100
conditions=(store_exp>2500000)&(total_profit_exp>700000)&(profit_margin>0.25)
expansion_eligible=np.where(conditions,stores,"Not eligible")
for store_exp in expansion_eligible:
    if store_exp != "Not eligible":
        print(f"Eligible Stores: {store_exp}")

print("\nCOST OPTIMIZATION")
print("-"*18)
store_index_for_co = 0
store_name_for_co = stores[store_index_for_co]
cost_store_for_co = cost_data[store_index_for_co]
sales_store_for_co = sales_data[store_index_for_co]
worst_margin_co = 100.0
worst_category_name_co = ""
worst_category_cost_co = 0

for c_idx in range(len(categories)):
    sales_category = sales_store_for_co[c_idx]
    cost_category = cost_store_for_co[c_idx]

    if sales_category > 0:
        profit_category = sales_category - cost_category
        profit_margin_category = (profit_category / sales_category) * 100

        if profit_margin_category < worst_margin_co:
            worst_margin_co = profit_margin_category
            worst_category_name_co = categories[c_idx]
            worst_category_cost_co = cost_category
print(f"Store: {store_name_for_co}")
print(f"Category: {worst_category_name_co}")
print(f"Cost: {worst_category_cost_co}")
print(f"Profit Margin: {worst_margin_co:.2f}")

print("\nINVENTORY REORDER")
print("-"*18)
closing_stock = opening_stock - units_sold
threshold_qty = 25
target_qty = 100
reorder_qty_matrix = np.where(closing_stock < threshold_qty, target_qty - closing_stock, 0)
reorder_needed_indices = np.where(reorder_qty_matrix > 0)

if len(reorder_needed_indices) == 0:
    print("No inventory reorder needed based on the current criteria.")
else:
    for r_idx, c_idx in zip(*reorder_needed_indices):
        print(f"Store: {stores[r_idx]}")
        print(f"Category: {categories[c_idx]}")
        print(f"Closing Stock: {closing_stock[r_idx, c_idx]}")
        print(f"Reorder Quantity: {reorder_qty_matrix[r_idx, c_idx]}")
        print("="*30)

SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34

BEST-PERFORMING STORE
---------------------
Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000
Profit Margin: 26.77

MOST PROFITABLE CATEGORY
------------------------
Category: Electronics
Sales: 4290000
Cost: 3250000
Profit:1040000
Profit Margin: 24.24

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores: Mumbai

COST OPTIMIZATION
------------------
Store: Bengaluru
Category: Electronics
Cost: 640000
Profit Margin: 24.71

INVENTORY REORDER
------------------
Store: Pune
Category: Furniture
Closing Stock: 20
Reorder Quantity: 80
